baseurl: ''
languageCode: de
title: midzers Archiv
googleAnalytics: ""
disqusShortname: ""
preserveTaxonomyNames: true
footnotereturnlinkcontents: ↩
disableHugoGeneratorInject: true
pluralizeListTitles: false
pygmentsCodeFences: false
pygmentsUseClasses: false
minify: false
paginate: 9999
disableKinds:
  - section
  - categories
  - tags

params:
  description: "Twitter Archiv (2014 bis 2022) von midzer"

frontmatter:
  author: midzer
  github: 'https://github.com/midzer'
  facebook: 
  og_image: 
  sitename: midzers Archiv
  twitter: '@midzer'

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

outputFormats:
  RSS:
    mediatype: application/rss
    baseName: atom
  JSON:
    mediatype: application/json
    baseName: feed
